services:
  backend:
    build: .
    container_name: urbanmove_backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET:-urbanmove_secret_key}
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    restart: always

  frontend:
    build: ./frontend
    container_name: urbanmove_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
